### ISSUE TITLE
Compression Slider Not Functioning

### ISSUE THREAD

**Issue by mareising** [chekuhakim/paperweight#1]
The interface works well, but whether you have the slider set to 10% or 90% the output is always exactly the same and is extremely aggressive compression to the point where it is barely legible.  
<img width="498" alt="Compression Issue" src="https://github.com/chekuhakim/paperweight/assets/142040904/08eef83b-997d-4d86-839e-1e67eb254e4c">

**Comment by mareising** [comment]
It looks like this is implemented using Ghostscript 9 instead of 10. Maybe that would help?

**Comment by chekuhakim** [comment]
the problem using the slider is that in the python code i specified in the interval of 10 20 30 but in slider in interval of 1. i changed to dropdown menu and now it is working again. you can test it now . tell me it is fixed

**Comment by mareising** [comment]
It looks like you changed from a slider to a drop down.  The result is actually slightly worse now.  Both High Quality and Low Quality settings result in the same output kB file, however now Adobe Reader complains that the file is corrupted. 
Could I also request that you look at the duplicate entries in the drop down? Its also a little counter intuitive that "High Quality" is the lowest quality. I'd suggest doing "High Compression" or similar as a more intuitive label. 
<img width="176" alt="2024-05-02 09_02_19-Compress PDF" src="https://github.com/chekuhakim/paperweight/assets/142040904/fc237d9f-b4a9-4ce0-aecf-873fbd4cb6d0">

**Comment by chekuhakim** [comment]
woah. its weird let me fix real quick

**Comment by chekuhakim** [comment]
okay i have fixed it. should be okay

**Comment by mareising** [comment]
There's still an issue. Although default now exports at 369 kB with decent middle of the road quality, both "high resolution" and "low resolution" still both output the exact same 92 kB file that is barely readable.
